src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom = null;

    #[ORM\OneToMany(targetEntity: Article::class, mappedBy: 'auteur')]
    private Collection $articles;

    #[ORM\OneToMany(targetEntity: Commentaire::class, mappedBy: 'auteur')]
    private Collection $commentaires;

    public function __construct()
    {
        $this->articles = new ArrayCollection();
        $this->commentaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    /**
     * @return Collection<int, Article>
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Article $article): static
    {
        if (!$this->articles->contains($article)) {
            $this->articles->add($article);
            $article->setAuteur($this);
        }

        return $this;
    }

    public function removeArticle(Article $article): static
    {
        if ($this->articles->removeElement($article)) {
            // set the owning side to null (unless already changed)
            if ($article->getAuteur() === $this) {
                $article->setAuteur(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Commentaire>
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): static
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires->add($commentaire);
            $commentaire->setAuteur($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): static
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getAuteur() === $this) {
                $commentaire->setAuteur(null);
            }
        }

        return $this;
    }
}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class SecurityController extends AbstractController
{
    #[Route(path: '/connexion/login', name: 'app_login')]
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        if ($this->getUser()) {
            return $this->redirectToRoute('app_article_index');
        }

        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login.html.twig', ['last_username' => $lastUsername, 'error' => $error]);
    }

    #[Route(path: '/connexion/logout', name: 'app_logout')]
    public function logout(): void
    {
        throw new \LogicException('This method can be blank - it will be intercepted by the logout key on your firewall.');
    }
}

templates/security/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}Log in!{% endblock %}

{% block stylesheets %}

<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1"> 
	<meta name="keywords" content="" />
	<meta name="author" content="" />
	<meta name="robots" content="" />
    <meta name="description" content="Davur - Restaurant Django Admin Dashboard + FrontEnd" />
	<meta property="og:title" content="Davur - Restaurant Django Admin Dashboard + FrontEnd" />
	<meta property="og:description" content="Davur - Restaurant Django Admin Dashboard + FrontEnd" />
	<meta property="og:image" content="https://davur.dexignzone.com/django/social-image.png" />
	<meta name="format-detection" content="telephone=no">
    <title>Davur - Restaurant Django Admin Dashboard + FrontEnd</title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="{{asset('static/frontend/images/favicon.png')}}">


    

    
    <link rel="stylesheet" href="{{asset('static/davur/vendor/bootstrap-select/dist/css/bootstrap-select.min.css')}}">
    
    <link rel="stylesheet" href="{{asset('static/davur/css/style.css')}}">
        {% endblock %}


        {% block javascripts %}
        
<script src="{{asset('static/davur/vendor/global/global.min.js')}}"></script>

<script src="{{asset('static/davur/vendor/bootstrap-select/dist/js/bootstrap-select.min.js')}}"></script>





<script src="{{asset('static/davur/js/custom.js')}}"></script>

<script src="{{asset('static/davur/js/deznav-init.js')}}"></script>




<script>
	$("#Admin").click(function() {
	  let email = document.getElementById("id_email");
	  email.value = "admin@example.com";
	  let password = document.getElementById("dz-password")
	  password.value = "asdf@1234";
	});
	$("#Manager").click(function() {
	  let email = document.getElementById("id_email").value = "manager@example.com";
	  let password = document.getElementById("dz-password").value = "asdf@1234";
	});
	$("#Customer").click(function() {
	  let email = document.getElementById("id_email").value = "customer@example.com";
	  let password = document.getElementById("dz-password").value = "asdf@1234";
	});
  </script>

        {% endblock %}

{% block body %}

<!DOCTYPE html>
<html lang="en" class="h-100">

<head>
	
    
    
    
    
    

</head>

<body class="h-100">
    {% if error %}
        <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
    {% endif %}

    {% if app.user %}
        <div class="mb-3">
            You are logged in as {{ app.user.userIdentifier }}, <a href="{{ path('app_logout') }}">Logout</a>
        </div>
    {% endif %}
    <div class="authincation h-100">
        <div class="container h-100">
            <div class="row justify-content-center h-100 align-items-center">
                <div class="col-md-6">
                    <div class="authincation-content">
                        <div class="row no-gutters">
                            <div class="col-xl-12">
                                <div class="auth-form">
									<div class="text-center mb-3">
										<a href="/index/"><img src="/static/davur/images/logo-full.png" alt=""></a>
									</div>
                                    <h4 class="text-center mb-4">Connectez vous a votre compte</h4>

									




 
                                    <form method="post" action="{{path('app_login')}}"><input type="hidden" name="csrfmiddlewaretoken" value="wvuIOarf0U23KtaWRIkPZAxkT6dCu9AgPz54HmFEZf86YqE5MdZLQnv7DFbm4zSA">
                                        <div class="form-group">
                                            <label class="mb-1"><strong>Email</strong></label>
											<input type="email" value="{{ last_username }}" name="email" id="inputEmail" class="form-control" autocomplete="email" required autofocus>
											<div class="text-danger w-100 d-block mt-1">
											  
											</div>
                                        </div>
                                        <div class="form-group">
                                            <label class="mb-1"><strong>Password</strong></label>
											<input type="password" name="password" id="inputPassword" class="form-control" autocomplete="current-password" required>
                                            <div class="text-danger w-100 d-block mt-1">
											  
											</div>
                                        </div>
                                        <input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}">
                                        <div class="form-row d-flex justify-content-between mt-4 mb-2 flex-wrap">
                                            <div class="form-group">
                                               <div class="custom-control custom-checkbox me-2 ">
													<input type="checkbox" class="form-check-input mt-0" id="basic_checkbox_1">
													<label class="custom-control-label ms-2 mb-0" for="basic_checkbox_1">Remember my preference</label>
												</div>
                                            </div>
                                            <div class="form-group">
                                                <a href="#">Forgot Password?</a>
                                            </div>
                                        </div>
                                        <div class="text-center">
                                            <button type="submit" class="btn btn-primary btn-block">Valider</button>
                                        </div>
                                    </form>
                                    <div class="new-account mt-3">
                                        <p>Vous avez pas encore de compte ? <a class="text-primary" href="/register/">Inscription</a></p>
                                    </div>
                                <hr/>
                             
								
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
<!--**********************************
	Scripts
***********************************-->
<!-- Required vendors -->


</html>


{% endblock %}