src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Titre = null;

    #[ORM\Column(length: 255)]
    private ?string $Contenu = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateCreation = null;

    #[ORM\Column]
    private ?bool $etat = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateparution = null;

    #[ORM\ManyToOne(inversedBy: 'articles')]
    private ?User $auteur = null;

    #[ORM\ManyToOne(inversedBy: 'articles')]
    private ?Categorie $categorie = null;

    #[ORM\OneToMany(targetEntity: Commentaire::class, mappedBy: 'article',cascade:["remove"])]
    private Collection $commentaires;

    public function __construct()
    {
        $this->commentaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): static
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->Contenu;
    }

    public function setContenu(string $Contenu): static
    {
        $this->Contenu = $Contenu;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->dateCreation;
    }

    public function setDateCreation(\DateTimeInterface $dateCreation): static
    {
        $this->dateCreation = $dateCreation;

        return $this;
    }

    public function isEtat(): ?bool
    {
        return $this->etat;
    }

    public function setEtat(bool $etat): static
    {
        $this->etat = $etat;

        return $this;
    }

    public function getDateparution(): ?\DateTimeInterface
    {
        return $this->dateparution;
    }

    public function setDateparution(\DateTimeInterface $dateparution): static
    {
        $this->dateparution = $dateparution;

        return $this;
    }

    public function getAuteur(): ?User
    {
        return $this->auteur;
    }

    public function setAuteur(?User $auteur): static
    {
        $this->auteur = $auteur;

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): static
    {
        $this->categorie = $categorie;

        return $this;
    }

    /**
     * @return Collection<int, Commentaire>
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): static
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires->add($commentaire);
            $commentaire->setArticle($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): static
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getArticle() === $this) {
                $commentaire->setArticle(null);
            }
        }

        return $this;
    }
}

src/Entity/Commentaire.php
<?php

namespace App\Entity;

use App\Repository\CommentaireRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentaireRepository::class)]
class Commentaire
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Commentaire = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $Datepublication = null;

    #[ORM\Column]
    private ?bool $Etat = null;

    #[ORM\ManyToOne(inversedBy: 'commentaires')]
    private ?User $auteur = null;

    #[ORM\ManyToOne(inversedBy: 'commentaires')]
    private ?Article $article = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCommentaire(): ?string
    {
        return $this->Commentaire;
    }

    public function setCommentaire(string $Commentaire): static
    {
        $this->Commentaire = $Commentaire;

        return $this;
    }

    public function getDatepublication(): ?\DateTimeInterface
    {
        return $this->Datepublication;
    }

    public function setDatepublication(\DateTimeInterface $Datepublication): static
    {
        $this->Datepublication = $Datepublication;

        return $this;
    }

    public function isEtat(): ?bool
    {
        return $this->Etat;
    }

    public function setEtat(bool $Etat): static
    {
        $this->Etat = $Etat;

        return $this;
    }

    public function getAuteur(): ?User
    {
        return $this->auteur;
    }

    public function setAuteur(?User $auteur): static
    {
        $this->auteur = $auteur;

        return $this;
    }

    public function getArticle(): ?Article
    {
        return $this->article;
    }

    public function setArticle(?Article $article): static
    {
        $this->article = $article;

        return $this;
    }
}

src/Form/CommentaireType.php
<?php

namespace App\Form;

use App\Entity\Article;
use App\Entity\Commentaire;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommentaireType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Commentaire')
            ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Commentaire::class,
        ]);
    }
}

src/Controller/CommentaireController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Entity\Commentaire;
use App\Form\CommentaireType;
use App\Repository\CommentaireRepository;
use DateTime;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

use function Symfony\Component\Clock\now;

#[Route('/commentaire')]
class CommentaireController extends AbstractController
{
    #[Route('/', name: 'app_commentaire_index', methods: ['GET'])]
    public function index(CommentaireRepository $commentaireRepository): Response
    {
        return $this->render('commentaire/index.html.twig', [
            'commentaires' => $commentaireRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_commentaire_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $commentaire = new Commentaire();
        $form = $this->createForm(CommentaireType::class, $commentaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($commentaire);
            $entityManager->flush();

            return $this->redirectToRoute('app_commentaire_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('commentaire/new.html.twig', [
            'commentaire' => $commentaire,
            'form' => $form,
        ]);
    }

    

    #[Route('/{id}', name: 'app_commentaire_show', methods: ['GET'])]
    public function show(Commentaire $commentaire ): Response
    {

        
        return $this->render('commentaire/show.html.twig', [
            'commentaire' => $commentaire,
            
        ]);
    }


    #[Route('commentaire/{id}', name: 'commenterarticle', methods: ['GET','POST'])]
    public function commenterarticle(Article $article, Request $request, EntityManagerInterface $entityManager): Response
    {

        $commentaire = new Commentaire();
        $form = $this->createForm(CommentaireType::class, $commentaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $date = new DateTime();
            $commentaire->setArticle($article);
            $commentaire->setDatepublication($date);
            $commentaire->setAuteur($this->getUser());
            $commentaire->setEtat(true);
            $entityManager->persist($commentaire);
            $entityManager->flush();

            return $this->redirectToRoute('app_article_index', [], Response::HTTP_SEE_OTHER);
        }
        return $this->render('commentaire/commenterarticle.html.twig', [
            'commentaire' => $commentaire,
            'form'=>$form->createView()
        ]);
    }


    #[Route('/activer/{id}', name: 'app_comm_active', methods: ['GET'])]
    public function ActiverCommentaire(Commentaire $commentaire,EntityManagerInterface $em,CommentaireRepository $commentaireRepository): Response
    {
        $commentaire->setEtat(true);
        $em->persist($commentaire);
        $em->flush();
        return $this->render('commentaire/index.html.twig', [
            'commentaires' => $commentaireRepository->findAll(),
        ]);
    }


    #[Route('/active_desactive/{id}', name: 'app_comm_activ_desactive', methods: ['GET'])]
    public function ActiverDesactiverCommentaire(Commentaire $commentaire,EntityManagerInterface $em,CommentaireRepository $commentaireRepository): Response
    {
        if ($commentaire->isEtat() == false) {
            $commentaire->setEtat(true);
        $em->persist($commentaire);
        $em->flush();
        }else{
            $commentaire->setEtat(false);
        $em->persist($commentaire);
        $em->flush();
        }

        
        return $this->render('commentaire/index.html.twig', [
            'commentaires' => $commentaireRepository->findAll(),
        ]);
    }


    #[Route('/{id}/edit', name: 'app_commentaire_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Commentaire $commentaire, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(CommentaireType::class, $commentaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_commentaire_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('commentaire/edit.html.twig', [
            'commentaire' => $commentaire,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_commentaire_delete', methods: ['POST'])]
    public function delete(Request $request, Commentaire $commentaire, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$commentaire->getId(), $request->request->get('_token'))) {
            $entityManager->remove($commentaire);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_commentaire_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/commentaire/_delete_form.html.twig
<form method="post" action="{{ path('app_commentaire_delete', {'id': commentaire.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ commentaire.id) }}">
    <button class="btn">Delete</button>
</form>

templates/commentaire/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/commentaire/commenterarticle.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Commentaire{% endblock %}

{% block body %}
    <h1>Create new Commentaire</h1>

    {{ include('commentaire/_form.html.twig') }}

    <a href="{{ path('app_commentaire_index') }}">back to list</a>
{% endblock %}

templates/commentaire/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Commentaire{% endblock %}

{% block body %}
    <h1>Edit Commentaire</h1>

    {{ include('commentaire/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_commentaire_index') }}">back to list</a>

    {{ include('commentaire/_delete_form.html.twig') }}
{% endblock %}

templates/commentaire/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commentaire index{% endblock %}

{% block body %}
    <h1>Commentaire index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Commentaire</th>
                <th>Datepublication</th>
                <th>Article</th>
                <th>Etat</th>
                {% if is_granted("ROLE_ADMIN") %}
                <th>actions</th>
                    {% else %}

                    {% endif %}
                
            </tr>
        </thead>
        <tbody>
        {% for commentaire in commentaires %}
            <tr>
                <td>{{ commentaire.id }}</td>
                <td>{{ commentaire.Commentaire }}</td>
                <td>{{ commentaire.Datepublication ? commentaire.Datepublication|date('Y-m-d H:i:s') : '' }}</td>
                <th>{{ commentaire.article.titre}}</th>
                <td>{{ commentaire.Etat ? 'Activé' : 'Désactivé' }}</td>
                <td>
                    {% if is_granted("ROLE_ADMIN") %}
                    <a href="{{path('app_comm_activ_desactive', {'id' : commentaire.id })}}">{{ commentaire.Etat ? 'Désactiver' : 'Activer' }}</a>
                    <a href="{{ path('app_commentaire_show', {'id': commentaire.id}) }}">show</a>
                    <a href="{{ path('app_commentaire_edit', {'id': commentaire.id}) }}">edit</a>
                    
                    {% else %}

                    {% endif %}

                    </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% if is_granted("ROLE_ADMIN") %}
    
    {% else %}

    {% endif %}

    
{% endblock %}

templates/commentaire/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Commentaire{% endblock %}

{% block body %}
    <h1>Create new Commentaire</h1>

    {{ include('commentaire/_form.html.twig') }}

    <a href="{{ path('app_commentaire_index') }}">back to list</a>
{% endblock %}

templates/commentaire/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commentaire{% endblock %}

{% block body %}
    <h1>Commentaire</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ commentaire.id }}</td>
            </tr>
            <tr>
                <th>Commentaire</th>
                <td>{{ commentaire.Commentaire }}</td>
            </tr>
            <tr>
                <th>Datepublication</th>
                <td>{{ commentaire.Datepublication ? commentaire.Datepublication|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Etat</th>
                <td>{{ commentaire.Etat ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_commentaire_index') }}">back to list</a>


    {% if is_granted('ROLE_ADMIN') %}
	
    <a href="{{ path('app_commentaire_edit', {'id': commentaire.id}) }}">edit</a>

    {{ include('commentaire/_delete_form.html.twig') }}

    {% elseif is_granted('ROLE_USER') %}
	
    {% else %}

	{% endif %}
						

  
{% endblock %}